version: "3"


services: 
  database:
    image: mysql:latest
    container_name: database
    networks:
      - mynet
    volumes:
      - mydb:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=<your_root_password>
      - MYSQL_DATABASE=<your_wordpress_database_name>
      - MYSQL_USER=<your_wordpress_database_user>
      - MYSQL_PASSWORD=<your_wordpress_database_password>

  wordpress:
    image: wordpress:5.9-php7.4-fpm-alpine
    container_name: wordpress
    networks:
      - mynet
    volumes:
      - mywp:/var/www/html/
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=<your_wordpress_database_user>
      - WORDPRESS_DB_PASSWORD=<your_wordpress_database_password>
      - WORDPRESS_DB_NAME=<your_wordpress_database_name>


  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
      - "443:443"
    container_name: nginx
    networks:
      - mynet
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - mywp:/var/www/html/
      - certbot-etc:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - mywp:/var/www/html/
    command: certonly --webroot --webroot-path=/var/www/html --email devops@gmail.com --agree-tos --no-eff-email --force-renewal  -d example.com -d www.example.com

networks:
  mynet:


volumes:
  mywp:
  mydb:
  certbot-etc:

